title: Dododo
lang: en-US
description: >-
  The open-source community rhythm game with musical notations
baseurl: ""
url: "https://dododogame.github.io"
github_username: dododogame
discord_invite_id: yYdMw5hm2K
discord_server_name: Dododo
telegram_username: dododogame
markdown: kramdown
kramdown:
  auto_ids: true
theme: minima
google_analytics: G-7HT2EELHML
show_excerpts: true
minima:
  date_format: "%b %-d, %Y"
header_pages:
  - about.md
  - blog.md
  - wiki.html
collections:
  posts:
    output: true
    permalink: /blog/:name
defaults:
  - scope:
      path: "wiki"
    values:
      toc: true
toc:
  ordered_list: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll_custom_permalink
  - jekyll-toc
feed:
  path: /blog/feed.xml
disqus:
  shortname: dododogame
exclude:
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Rakefile
  - pkg/
  - README.md
  - LICENSE
  - "**/node_modules/"
  - "**/README.md"
  - "**/LICENSE"
  - "**/gemfiles"
  - "**/Gemfile"
  - "**/Gemfile.lock"
  - "**/vendor/bundle"
  - "**/vendor/cache"
  - "**/vendor/gems"
  - "**/vendor/ruby"
  - "**/pkg"
  - "**/Rakefile"
